name: Build Docker image

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  pull_request:
    branches: ['main']


# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
    build-gromacs-image:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            arch: [amd64]
            gmx_opts:
              - ""
              - "-DGMX_GPU=CUDA"
              - "-DGMX_GPU=CUDA -DGMX_THREAD_MPI=ON"
              - "-DGMX_GPU=CUDA -DGMX_MPI=ON"
        # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
        permissions:
          contents: read
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
          # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
          - name: Log in to the Container registry
            uses: docker/login-action@v3
    
          - name: Convert compiler options to simple tag suffix
            id: tag_suffix
            run: |
              if [[ "${{ matrix.gmx_opts }}" == *"THREAD"* ]]; then
                echo "tag_suffix=GPU-Thread-MPI" >> $GITHUB_ENV
              elif [[ "${{ matrix.gmx_opts }}" == *"MPI"* ]]; then
                echo "tag_suffix=GPU-Node-MPI" >> $GITHUB_ENV
              elif [[  "${{ matrix.gmx_opts }}" == *"GPU"* ]]; then
                echo "tag_suffix=GPU" >> $GITHUB_ENV
              else
                echo "tag_suffix=Single-Core-CPU" >> $GITHUB_ENV
              fi

          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
              context: ./docker/gromacs
              push: false
              build-args: 
                GMX_OPTS=${{ matrix.gmx_opts }}

    build-lammps-image:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          arch: [amd64]
          lmp_opts:
            - ""
            - "-D PKG_GPU=on -D GPU_API=cuda"
            - "-D PKG_GPU=on -D GPU_API=cuda -D BUILD_MPI=yes"
      # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
      permissions:
        contents: read
        packages: write
        # 
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
        - name: Log in to the Container registry
          uses: docker/login-action@v3
  
        - name: Convert compiler options to simple tag suffix
          id: tag_suffix
          run: |
            if [[ "${{ matrix.lmp_opts }}" == *"MPI"* ]]; then
              echo "tag_suffix=GPU-Node-MPI" >> $GITHUB_ENV
            elif [[ "${{ matrix.lmp_opts }}" == *"GPU"* ]]; then
              echo "tag_suffix=GPU" >> $GITHUB_ENV
            else
              echo "tag_suffix=Single-Core-CPU" >> $GITHUB_ENV
            fi

        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: ./docker/lammps
            push: false
            build-args: |
              LMP_OPTS=${{ matrix.lmp_opts }}
        
    build-namd-image:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            arch: [amd64]
            namd_opts:
              - ""
              - "--with-cuda"
        # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
        permissions:
          contents: read

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
          # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
          - name: Log in to the Container registry
            uses: docker/login-action@v3
    
          - name: Convert compiler options to simple tag suffix
            id: tag_suffix
            run: |
              if [[ "${{ matrix.namd_opts }}" == *"cuda"* ]]; then
                echo "tag_suffix=GPU" >> $GITHUB_ENV
              else
                echo "tag_suffix=Single-Core-CPU" >> $GITHUB_ENV
              fi

          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
              context: ./docker/namd
              push: false
              build-args: |
                NAMD_OPTS=${{ matrix.namd_opts }}