name: Build Docker image

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  pull_request:
    branches: ['main']


# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
    build-gromacs-image:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            arch: [amd64]
            gmx_opts:
              - ""
              - "-DGMX_GPU=CUDA"
              - "-DGMX_GPU=CUDA -DGMX_THREAD_MPI=ON"
              - "-DGMX_GPU=CUDA -DGMX_MPI=ON"
        # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
        permissions:
          contents: read
        steps:
          - name: Free disk space
            uses: jlumbroso/free-disk-space@main
            with:
              android: true
              dotnet: true
              haskell: true
              large-packages: true
              swap-storage: true
          
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Convert compiler options to simple tag suffix
            id: tag_suffix
            run: |
              if [[ "${{ matrix.gmx_opts }}" == *"THREAD"* ]]; then
                echo "tag_suffix=GPU-Thread-MPI" >> $GITHUB_ENV
              elif [[ "${{ matrix.gmx_opts }}" == *"MPI"* ]]; then
                echo "tag_suffix=GPU-Node-MPI" >> $GITHUB_ENV
              elif [[  "${{ matrix.gmx_opts }}" == *"GPU"* ]]; then
                echo "tag_suffix=GPU" >> $GITHUB_ENV
              else
                echo "tag_suffix=Single-Core-CPU" >> $GITHUB_ENV
              fi

          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
              context: ./docker/gromacs
              push: false
              build-args: 
                GMX_OPTS=${{ matrix.gmx_opts }}

    build-lammps-image:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          arch: [amd64]
          lmp_opts:
            - ""
            - "-D PKG_GPU=on -D GPU_API=cuda"
            - "-D PKG_GPU=on -D GPU_API=cuda -D BUILD_MPI=yes"
      # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
      permissions:
        contents: read
        
      steps:
        - name: Free disk space
          uses: jlumbroso/free-disk-space@main
          with:
            android: true
            dotnet: true
            haskell: true
            large-packages: true
            swap-storage: true
          
        - name: Checkout repository
          uses: actions/checkout@v4
  
        - name: Convert compiler options to simple tag suffix
          id: tag_suffix
          run: |
            if [[ "${{ matrix.lmp_opts }}" == *"MPI"* ]]; then
              echo "tag_suffix=GPU-Node-MPI" >> $GITHUB_ENV
            elif [[ "${{ matrix.lmp_opts }}" == *"GPU"* ]]; then
              echo "tag_suffix=GPU" >> $GITHUB_ENV
            else
              echo "tag_suffix=Single-Core-CPU" >> $GITHUB_ENV
            fi

        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: ./docker/lammps
            push: false
            build-args: |
              LMP_OPTS=${{ matrix.lmp_opts }}
        
    build-namd-image:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            arch: [amd64]
            namd_opts:
              - ""
              - "--with-cuda"
        # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
        permissions:
          contents: read

        steps:
          - name: Free disk space
            uses: jlumbroso/free-disk-space@main
            with:
              android: true
              dotnet: true
              haskell: true
              large-packages: true
              swap-storage: true

          - name: Checkout repository
            uses: actions/checkout@v4
    
          - name: Convert compiler options to simple tag suffix
            id: tag_suffix
            run: |
              if [[ "${{ matrix.namd_opts }}" == *"cuda"* ]]; then
                echo "tag_suffix=GPU" >> $GITHUB_ENV
              else
                echo "tag_suffix=Single-Core-CPU" >> $GITHUB_ENV
              fi

          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
              context: ./docker/namd
              push: false
              build-args: |
                NAMD_OPTS=${{ matrix.namd_opts }}

    build-common-image:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            arch: [amd64]
            build: ["Common-CPU", "Common-GPU"]

        permissions:
          contents: read

        steps:
          - name: Free disk space
            uses: jlumbroso/free-disk-space@main
            with:
              android: true
              dotnet: true
              haskell: true
              large-packages: true
              swap-storage: true

          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Option
            id: option
            run: |
              if [ "${{ matrix.build }}" == "Common-CPU" ]; then
                echo 'NAMD_OPTS=' >> $GITHUB_ENV
                echo 'GMX_OPTS=' >> $GITHUB_ENV
                echo 'LMP_OPTS=' >> $GITHUB_ENV
                echo 'RT_IMG=centos:7' >> $GITHUB_ENV
              else
                echo 'NAMD_OPTS=--with-cuda' >> $GITHUB_ENV
                echo 'GMX_OPTS=-DGMX_GPU=CUDA' >> $GITHUB_ENV
                echo 'LMP_OPTS=-D PKG_GPU=on -D GPU_API=cuda' >> $GITHUB_ENV
                echo 'RT_IMG=nvidia/cuda:11.8.0-runtime-centos7' >> $GITHUB_ENV
              fi

    
          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
              context: ./docker/common
              push: false
              build-args: |
                NAMD_OPTS=${{ env.NAMD_OPTS }}
                GMX_OPTS=${{ env.GMX_OPTS }}
                LMP_OPTS=${{ env.LMP_OPTS }}
                RT_IMG=${{ env.RT_IMG}}